// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4gUHEerevMbPRwqz5Wpu5_mTORY40Ys0',
    appId: '1:699348421681:web:6bcf276671bc3b42629910',
    messagingSenderId: '699348421681',
    projectId: 'fireprevention-6d950',
    authDomain: 'fireprevention-6d950.firebaseapp.com',
    storageBucket: 'fireprevention-6d950.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt3yOdEgNlalKXVEOyUp8h-EmSZNidGfc',
    appId: '1:699348421681:android:ae3acbd5b0843b25629910',
    messagingSenderId: '699348421681',
    projectId: 'fireprevention-6d950',
    storageBucket: 'fireprevention-6d950.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ11TqySpgdLh2WACVW_BvZFpge9rGUqs',
    appId: '1:699348421681:ios:048b161bde78b0d4629910',
    messagingSenderId: '699348421681',
    projectId: 'fireprevention-6d950',
    storageBucket: 'fireprevention-6d950.firebasestorage.app',
    iosClientId: '699348421681-7e0lsldcopm6pf583cgi1luq32jat5dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireprevention',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ11TqySpgdLh2WACVW_BvZFpge9rGUqs',
    appId: '1:699348421681:ios:562b372937b16a52629910',
    messagingSenderId: '699348421681',
    projectId: 'fireprevention-6d950',
    storageBucket: 'fireprevention-6d950.firebasestorage.app',
    iosClientId: '699348421681-4v62jnl8ml0fq31d1501vqopchvcb57p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firePrevention',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4gUHEerevMbPRwqz5Wpu5_mTORY40Ys0',
    appId: '1:699348421681:web:e8f90d378e560fbc629910',
    messagingSenderId: '699348421681',
    projectId: 'fireprevention-6d950',
    authDomain: 'fireprevention-6d950.firebaseapp.com',
    storageBucket: 'fireprevention-6d950.firebasestorage.app',
  );
}
